# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text="The comment's associated product SKU", max_length=8)),
                ('content', models.TextField(help_text="The comment's textual content")),
                ('created', models.DateTimeField(auto_now_add=True, help_text="The comment's creation date and time")),
                ('modified', models.DateTimeField(auto_now=True, help_text="The comment's most recent modification date and time")),
            ],
        ),
        migrations.CreateModel(
            name='CommentTone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tone_type', models.IntegerField(choices=[(0, 'anger'), (1, 'disgust'), (2, 'fear'), (3, 'joy'), (4, 'sadness')], help_text="The comment tone's type (joy, anger, etc)")),
                ('score', models.FloatField(help_text="The comment tone's score value")),
                ('created', models.DateTimeField(auto_now_add=True, help_text="The comment tone's creation date and time")),
                ('modified', models.DateTimeField(auto_now=True, help_text="The comment tone's most recent modification date and time")),
                ('comment_id', models.ForeignKey(help_text="The comment tone's associated comment", on_delete=django.db.models.deletion.CASCADE, related_name='tones', to='api.Comment')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='commenttone',
            unique_together=set([('comment_id', 'tone_type')]),
        ),
    ]
